---
title: "String Practice"
author: "Josephine Cardelle"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

# Task 3: Practice with Strings
```{r}
alarm_report <- data.frame(
  stringsAsFactors = FALSE,
              date = c("2020-03-14", "2020-03-15", "2020-04-10", "2020-04-18"),
          building = c("Engineering-North",
                       "Bren Hall","Engineering-South","Engr-North"),
     alarm_message = c("10:02am -- HVAC system down, facilities management alerted",
                       "8:24am -- Elevator North out of service",
                       "12:41am -- Fire alarm, UCSB fire responded and cleared",
                       "9:58pm -- Campus point emergency siren, UCPD responded")
)
```

```{r}
alarm_report <- alarm_report %>%
  mutate(building = str_replace(building, pattern = "Engr", replacement = "Engineering"))

alarm_report <- alarm_report %>%
  separate(col = building, into = c("building", "wing"), sep = "-")

alarm_report <- alarm_report %>%
  separate(col = alarm_message, into = c("message-time", "alarm-message"), sep = "--")

alarm_report <- alarm_report %>%
  mutate(date = lubridate::ymd(date))

alarm_report <- alarm_report %>%
  filter(str_detect(.$`alarm-message`, "responded"))
```

